### ISSUE TITLE
Cant setup

### ISSUE THREAD

**Issue by VonOx** [GladysProject/gladys-hue#4]
The initial configuration ( Click button ) in the instruction doesn't exist

Thank you

**Comment by Pierre-Gilles** [comment]
Hey! 

Have you installed Gladys manually from the GitHub?

Because on master branch we have a new feature that remove this button, and since we haven't published the release for Gladys users, we haven't had the time to adapt this module yet to the new way of doing. 

Please use the latest release of Gladys, Gladys v3.8.1, by setting your git installation to the v3.8.1 tag. 

Thanks :)

**Comment by Pierre-Gilles** [comment]
Yes, but the docker image is based on Gladys master latest! 

But you can spin up a Docker version of Gladys based on a tag =>

gladysproject/gladys:v3.8.1

**Comment by VonOx** [comment]
@Pierre-Gilles a stable tag would be usefull.
In case you are using https://github.com/v2tec/watchtower like me, gladys is autoupdated. "stable" tag ( or latest release ) is such interresting.

**Comment by VonOx** [comment]
It's OK with 3.8.1, what do you think about new tag?

**Comment by Pierre-Gilles** [comment]
Ok I understand! :) didn't know about watchtower, useful project!

Could be great to have indeed a "stable" tag that corresponds to the most recent tag. 

Only thing is that I don't know if it's possible with only Docker Hub, i think I'm going to have to do it through a custom build on CircleCI or TravisCI...

**Comment by Pierre-Gilles** [comment]
I created a card on Trello btw

**Comment by VonOx** [comment]
Yep custom build and push to docker hub. I close this issue. Can you add me in trello board ( @vonox)

Thank you
